---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/kidibox/nixlab
    targetRevision: argocd-test
    path: gitops/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
