---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer
  labels:
    app: overseer
spec:
  selector:
    matchLabels:
      app: overseer
  replicas: 1
  strategy:
    #   rollingUpdate:
    #     maxSurge: 25%
    #     maxUnavailable: 25%
    type: Recreate
  template:
    metadata:
      labels:
        app: overseer
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: overseer-config
      containers:
        - name: overseer
          image: lscr.io/linuxserver/overseerr:latest
          restartPolicy: Always
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          # livenessProbe:
          #   tcpSocket:
          #     port: 80
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 80
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 3
          #   periodSeconds: 10
          env:
            - name: LOG_LEVEL
              value: debug
            - name: TZ
              value: Europe/Brussels
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
