apiVersion: v1
kind: ConfigMap
metadata:
  name: openebs-zfspv-bin
  namespace: kube-system
data:
  zfs: |
    #!/bin/sh
    if [ -x /host/sbin/zfs ]; then
      chroot /host /sbin/zfs "$@"
    elif [ -x /host/usr/sbin/zfs ]; then
      chroot /host /usr/sbin/zfs "$@"
    elif [ /host/run/current-system ]; then
      chroot /host /run/current-system/sw/bin/zfs "$@"
    else
      chroot /host zfs "$@"
    fi
