---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-overseer
  namespace: flux-system
spec:
  dependsOn:
    - name: addons-cert-manager-issuers
    - name: addons-zfs-localpv
  targetNamespace: overseer
  path: ./kubernetes/apps/overseer/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
