---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
allowVolumeExpansion: true
parameters:
  dedup: "off"
  fstype: "zfs"
  poolname: "zroot/openebs"
provisioner: zfs.csi.openebs.io
