---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: zfs-localpv
        namespace: openebs
      interval: 12h
