---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-localpv
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./deploy/yamls
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: openebs-zfs-localpv
  targetNamespace: openebs
  timeout: 3m0s
  wait: true
