---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openebs-zfs-localpv
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/openebs/zfs-localpv
  ref:
    branch: v2.3.0
