apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  bootstrap: true
  repo: https://helm.cilium.io/
  chart: cilium
  version: 1.14.3
  targetNamespace: kube-system
  valuesContent: |-
    k8sServiceHost: 10.0.100.189
    k8sServicePort: 6443
    kubeProxyReplacement: true

    # k3s specific
    cni:
      binPath: /var/lib/rancher/k3s/agent/opt/cni/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d

    bpf:
      # does this makes senses with native routing?
      masquerade: true

    # this breaks ingress on same node
    # routingMode: native
    # ipv4NativeRoutingCIDR: 10.42.0.0/16
    # auto-direct-node-routes: true
    # endpointRoutes:
    #   enabled: true

    bgpControlPlane:
      enabled: true
    operator:
      replicas: 1
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16


    # ingressController:
    #   enabled: true
    #   loadbalancerMode: dedicated
    gatewayAPI:
      enabled: false

    hubble:
      ui:
        enabled: true
      relay:
        enabled: true
