routeros_username: ENC[AES256_GCM,data:iGDVLb8=,iv:rDsjTtcYHPeG2g8h4BkaBfTiZ5s78o+nuAr3VUETCSA=,tag:vSWnSXnnE8KPDUZLwRTHWg==,type:str]
routeros_password: ENC[AES256_GCM,data:8cHDBbB4,iv:lYP6So1vp07xVuEU5Bdjr8dMLHzYLdKLyGlzJUUthrI=,tag:tCo6N5cgDnCsPY7PWIS1KA==,type:str]
routeros_insecure: ENC[AES256_GCM,data:hDeDow==,iv:c+i+iKcSWa9LVN/5fZVOO3biSVX6xx7+a+u5/SzE+7A=,tag:qNs6/3jidl5vfkBXZ4LiWw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dghfu7sxwlkf4626eywmgr63y2g7m4x8zs8a6xt2zay3x7dclpnsw776dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQkNiRU1wa3YvdlZEVWEz
            U0h5amloelhJQzFnKzBCaGFjWFBYVlN2UjJZClJIOTJrQ1VUcXh5UW0vcXJqMjhV
            dUZ4TjNWdDhmT0FoYVVCczg4T0pKaG8KLS0tIGpDQmpUcDJIQkZJa0g5b1pHV09p
            OHJMTW5TbVJ0dXJMWVN3M2RMWWNha1kK5EcuXUh0F3GRnAQ4u3xvPIZtYYS/mVRk
            8Ibn2eoWBqHZE0qTYwaWkHd1jh5jrA5fVlvxwlh6XKHyd1R9HKOz6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T10:24:25Z"
    mac: ENC[AES256_GCM,data:3RQpfaNtm3u8YgLnEhoPKiazy2UcWihPEOoSdJZSUuL0bMsvGV+6rL3yWyW8QaK6E2ld2S09zjynAaDTjUuuBW3DO5wVAexAa+KtAXLGjKrcF+6f3Q7yUsxLUWjPmFD/+VFAV7ZLl8VodlpaS87aHOszJufo4Pboha/oqvTbSQ8=,iv:GN9EYKZ+sKnHFvCoYiFYO9CgWxv51uQ0siSmGLnMMwA=,tag:oln28218/eOhbz5OAv2Yow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
