---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "kidibox-nixlab"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
