apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./bootstrap/github-deploy-key.sops.yaml
