name: nix flake check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_nix:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          # To avoid GitHub rate limiting
          extra_nix_config:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run nix flake checks
        run: nix flake check
